-- ============================================================================
-- VALORIZE PLATFORM - PART 2: BUSINESS LOGIC ENHANCEMENT
-- Database Migration Phase 2 - Advanced Business Rules and Systems
-- ============================================================================

-- This file enhances the core platform with:
-- - Structured company values system
-- - Advanced coin transaction tracking
-- - Praise reactions and social features
-- - Enhanced reward categorization  
-- - Business rule validations
-- - Performance optimization foundations

-- PREREQUISITES: Part 1 (01_core_tables.sql) must be executed first

-- ============================================================================
-- STRUCTURED COMPANY VALUES SYSTEM
-- ============================================================================

-- Replace the varchar company_value in compliments with a structured system
CREATE TABLE "company_values" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) NOT NULL UNIQUE, -- Internal code (e.g., 'INNOVATION')
  "name" varchar(100) NOT NULL,
  "description" text,
  "icon" varchar(200), -- Icon/image for UI
  "color" varchar(7), -- Hex color code for theming
  "active" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW()
);

-- Link compliments to structured company values
ALTER TABLE "compliment" ADD COLUMN "company_value_id" int;
ALTER TABLE "compliment" ADD FOREIGN KEY ("company_value_id") REFERENCES "company_values" ("id");

-- Create index for performance
CREATE INDEX "idx_compliment_company_value" ON "compliment" ("company_value_id");

-- ============================================================================
-- ADVANCED COIN TRANSACTION SYSTEM
-- ============================================================================

-- Detailed transaction tracking for audit and business intelligence
CREATE TABLE "coin_transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "transaction_type" varchar(20) NOT NULL, -- CREDIT, DEBIT
  "source_type" varchar(30) NOT NULL, -- COMPLIMENT_RECEIVED, REWARD_PURCHASE, INITIATIVE_COMPLETED, etc.
  "source_id" int, -- ID of the source record (compliment_id, redeem_id, etc.)
  "amount" int NOT NULL,
  "balance_before" int NOT NULL,
  "balance_after" int NOT NULL,
  "description" varchar(500),
  "metadata" jsonb, -- Additional transaction context
  "created_at" timestamptz NOT NULL DEFAULT NOW()
);

-- Add foreign key and indexes
ALTER TABLE "coin_transactions" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;
CREATE INDEX "idx_coin_transactions_user" ON "coin_transactions" ("user_id", "created_at");
CREATE INDEX "idx_coin_transactions_type" ON "coin_transactions" ("transaction_type", "source_type");
CREATE INDEX "idx_coin_transactions_source" ON "coin_transactions" ("source_type", "source_id");

-- ============================================================================
-- PRAISE SOCIAL FEATURES  
-- ============================================================================

-- Reactions to compliments (likes, hearts, etc.)
CREATE TABLE "compliment_reactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "compliment_id" int NOT NULL,
  "user_id" int NOT NULL,
  "reaction_type" varchar(20) NOT NULL DEFAULT 'LIKE', -- LIKE, HEART, CLAP, etc.
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE("compliment_id", "user_id", "reaction_type")
);

-- Comments on compliments for social engagement
CREATE TABLE "compliment_comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "compliment_id" int NOT NULL,
  "user_id" int NOT NULL,
  "comment" varchar(500) NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW()
);

-- Add foreign keys and indexes
ALTER TABLE "compliment_reactions" ADD FOREIGN KEY ("compliment_id") REFERENCES "compliment" ("id") ON DELETE CASCADE;
ALTER TABLE "compliment_reactions" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;
ALTER TABLE "compliment_comments" ADD FOREIGN KEY ("compliment_id") REFERENCES "compliment" ("id") ON DELETE CASCADE;
ALTER TABLE "compliment_comments" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;

CREATE INDEX "idx_compliment_reactions_compliment" ON "compliment_reactions" ("compliment_id");
CREATE INDEX "idx_compliment_reactions_user" ON "compliment_reactions" ("user_id");
CREATE INDEX "idx_compliment_comments_compliment" ON "compliment_comments" ("compliment_id");
CREATE INDEX "idx_compliment_comments_user" ON "compliment_comments" ("user_id");

-- ============================================================================
-- ENHANCED REWARDS CATEGORIZATION
-- ============================================================================

-- Structured reward categories with hierarchy support
CREATE TABLE "reward_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "slug" varchar(100) NOT NULL UNIQUE,
  "description" text,
  "icon" varchar(200),
  "color" varchar(7),
  "parent_id" int, -- For category hierarchy
  "active" boolean NOT NULL DEFAULT true,
  "sort_order" int NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW()
);

-- Self-referencing foreign key for hierarchy
ALTER TABLE "reward_categories" ADD FOREIGN KEY ("parent_id") REFERENCES "reward_categories" ("id");

-- Link rewards to structured categories
ALTER TABLE "rewards" ADD COLUMN "category_id" int;
ALTER TABLE "rewards" ADD FOREIGN KEY ("category_id") REFERENCES "reward_categories" ("id");

-- Indexes for category system
CREATE INDEX "idx_reward_categories_parent" ON "reward_categories" ("parent_id");
CREATE INDEX "idx_reward_categories_active" ON "reward_categories" ("active", "sort_order");
CREATE INDEX "idx_rewards_category" ON "rewards" ("category_id");

-- ============================================================================
-- INITIATIVE PARTICIPATION TRACKING
-- ============================================================================

-- Track user participation in initiatives beyond just credits
CREATE TABLE "initiative_participants" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "initiative_id" int NOT NULL,
  "user_id" int NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, COMPLETED, WITHDRAWN
  "joined_at" timestamptz NOT NULL DEFAULT NOW(),
  "completed_at" timestamptz,
  "progress_data" jsonb, -- Custom progress tracking
  "notes" text,
  UNIQUE("initiative_id", "user_id")
);

-- Add foreign keys and indexes
ALTER TABLE "initiative_participants" ADD FOREIGN KEY ("initiative_id") REFERENCES "initiatives" ("id") ON DELETE CASCADE;
ALTER TABLE "initiative_participants" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;

CREATE INDEX "idx_initiative_participants_initiative" ON "initiative_participants" ("initiative_id", "status");
CREATE INDEX "idx_initiative_participants_user" ON "initiative_participants" ("user_id", "status");

-- ============================================================================
-- REWARD WISHLIST SYSTEM
-- ============================================================================

-- User wishlist for rewards
CREATE TABLE "reward_wishlist" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "reward_id" int NOT NULL,
  "priority" int NOT NULL DEFAULT 1, -- 1=HIGH, 2=MEDIUM, 3=LOW
  "notes" varchar(500),
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE("user_id", "reward_id")
);

-- Foreign keys and indexes
ALTER TABLE "reward_wishlist" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;
ALTER TABLE "reward_wishlist" ADD FOREIGN KEY ("reward_id") REFERENCES "rewards" ("id") ON DELETE CASCADE;

CREATE INDEX "idx_reward_wishlist_user" ON "reward_wishlist" ("user_id", "priority");
CREATE INDEX "idx_reward_wishlist_reward" ON "reward_wishlist" ("reward_id");

-- ============================================================================
-- NOTIFICATION SYSTEM FOUNDATION
-- ============================================================================

-- Basic notification system for business events
CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "type" varchar(50) NOT NULL, -- COMPLIMENT_RECEIVED, REWARD_AVAILABLE, etc.
  "title" varchar(200) NOT NULL,
  "message" text NOT NULL,
  "data" jsonb, -- Additional notification data
  "read" boolean NOT NULL DEFAULT false,
  "read_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT NOW()
);

-- Foreign keys and indexes
ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;

CREATE INDEX "idx_notifications_user_unread" ON "notifications" ("user_id") WHERE "read" = false;
CREATE INDEX "idx_notifications_user_type" ON "notifications" ("user_id", "type", "created_at");
CREATE INDEX "idx_notifications_created" ON "notifications" ("created_at");

-- ============================================================================
-- BUSINESS RULE VALIDATIONS & CONSTRAINTS
-- ============================================================================

-- Ensure transaction amounts are valid
ALTER TABLE "coin_transactions" ADD CONSTRAINT "check_transaction_amount"
  CHECK ("amount" != 0); -- Prevent zero-amount transactions

-- Ensure balance calculations are consistent
ALTER TABLE "coin_transactions" ADD CONSTRAINT "check_balance_consistency"
  CHECK (
    ("transaction_type" = 'CREDIT' AND "balance_after" = "balance_before" + "amount") OR
    ("transaction_type" = 'DEBIT' AND "balance_after" = "balance_before" - "amount")
  );

-- Prevent negative coin balances
ALTER TABLE "coin_transactions" ADD CONSTRAINT "check_no_negative_balance"
  CHECK ("balance_after" >= 0);

-- Ensure comments are not empty
ALTER TABLE "compliment_comments" ADD CONSTRAINT "check_comment_not_empty"
  CHECK (LENGTH(TRIM("comment")) > 0);

-- Ensure category hierarchy doesn't create cycles
CREATE OR REPLACE FUNCTION check_category_hierarchy()
RETURNS TRIGGER AS $$
DECLARE
  current_id INT;
  max_depth INT := 10;
  depth INT := 0;
BEGIN
  IF NEW.parent_id IS NULL THEN
    RETURN NEW;
  END IF;
  
  current_id := NEW.parent_id;
  
  WHILE current_id IS NOT NULL AND depth < max_depth LOOP
    IF current_id = NEW.id THEN
      RAISE EXCEPTION 'Category hierarchy cycle detected';
    END IF;
    
    SELECT parent_id INTO current_id 
    FROM reward_categories 
    WHERE id = current_id;
    
    depth := depth + 1;
  END LOOP;
  
  IF depth >= max_depth THEN
    RAISE EXCEPTION 'Category hierarchy too deep (max 10 levels)';
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER check_category_hierarchy_trigger
  BEFORE INSERT OR UPDATE ON "reward_categories"
  FOR EACH ROW
  EXECUTE FUNCTION check_category_hierarchy();

-- ============================================================================
-- ADDITIONAL TRIGGERS FOR BUSINESS LOGIC
-- ============================================================================

-- Update triggers for new tables
CREATE TRIGGER update_company_values_updated_at BEFORE UPDATE ON "company_values" 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_reward_categories_updated_at BEFORE UPDATE ON "reward_categories" 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_compliment_comments_updated_at BEFORE UPDATE ON "compliment_comments" 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- BUSINESS INTELLIGENCE FOUNDATION
-- ============================================================================

-- Materialized view for compliment statistics (refresh periodically)
CREATE MATERIALIZED VIEW "mv_compliment_stats" AS
SELECT 
  cv.code as company_value_code,
  cv.name as company_value_name,
  COUNT(*) as total_compliments,
  AVG(c.quantity) as avg_coins,
  SUM(c.quantity) as total_coins,
  COUNT(DISTINCT c.id_sender_user) as unique_senders,
  COUNT(DISTINCT c.id_receiver_user) as unique_receivers,
  DATE_TRUNC('month', c.created_at) as month_year
FROM "compliment" c
JOIN "company_values" cv ON c.company_value_id = cv.id
WHERE c.created_at >= NOW() - INTERVAL '12 months'
GROUP BY cv.code, cv.name, DATE_TRUNC('month', c.created_at)
ORDER BY month_year DESC, total_compliments DESC;

-- Index for materialized view
CREATE INDEX "idx_mv_compliment_stats_month" ON "mv_compliment_stats" ("month_year");
CREATE INDEX "idx_mv_compliment_stats_value" ON "mv_compliment_stats" ("company_value_code");

-- ============================================================================
-- PERFORMANCE OPTIMIZATION VIEWS
-- ============================================================================

-- User dashboard data view (frequently accessed data)
CREATE VIEW "v_user_dashboard" AS
SELECT 
  u.id,
  u.name,
  u.email,
  u.coins_to_donate,
  u.coins_to_spend,
  -- Compliment stats
  (SELECT COUNT(*) FROM compliment WHERE id_receiver_user = u.id) as compliments_received,
  (SELECT COUNT(*) FROM compliment WHERE id_sender_user = u.id) as compliments_sent,
  (SELECT SUM(quantity) FROM compliment WHERE id_receiver_user = u.id) as total_coins_received,
  -- Recent activity
  (SELECT MAX(created_at) FROM compliment WHERE id_receiver_user = u.id OR id_sender_user = u.id) as last_compliment_activity,
  (SELECT MAX(created_at) FROM redeem WHERE id_user = u.id) as last_redemption,
  -- Notification count
  (SELECT COUNT(*) FROM notifications WHERE user_id = u.id AND read = false) as unread_notifications
FROM "user" u
WHERE u.active = true;

-- Reward catalog view with enriched data
CREATE VIEW "v_reward_catalog" AS
SELECT 
  r.id,
  r.title,
  r.description,
  r.image,
  r.price,
  r.active,
  r.brand,
  r.redeemed,
  r.limited,
  r.slug,
  r.created_at,
  rc.name as category_name,
  rc.slug as category_slug,
  rc.color as category_color,
  -- Stock info
  COALESCE(SUM(s.quantity), 0) as total_stock,
  -- Popularity metrics
  (SELECT COUNT(*) FROM reward_wishlist WHERE reward_id = r.id) as wishlist_count,
  (SELECT AVG(CASE WHEN created_at >= NOW() - INTERVAL '30 days' THEN 1 ELSE 0 END)) as recent_popularity
FROM "rewards" r
LEFT JOIN "reward_categories" rc ON r.category_id = rc.id
LEFT JOIN "stock" s ON r.id = s.id_reward
WHERE r.active = true
GROUP BY r.id, rc.name, rc.slug, rc.color;

-- ============================================================================
-- INITIAL BUSINESS DATA SETUP
-- ============================================================================

-- Default company values
INSERT INTO "company_values" ("code", "name", "description", "color", "sort_order", "active") VALUES
('INNOVATION', 'Innovation', 'Embracing creativity and new ideas to drive progress', '#FF6B6B', 1, true),
('COLLABORATION', 'Collaboration', 'Working together towards common goals and shared success', '#4ECDC4', 2, true),
('EXCELLENCE', 'Excellence', 'Striving for the highest quality in everything we do', '#45B7D1', 3, true),
('INTEGRITY', 'Integrity', 'Acting with honesty and strong moral principles', '#96CEB4', 4, true),
('CUSTOMER_FOCUS', 'Customer Focus', 'Putting our customers at the center of everything', '#FFEAA7', 5, true);

-- Default reward categories
INSERT INTO "reward_categories" ("name", "slug", "description", "color", "sort_order") VALUES
('Electronics', 'electronics', 'Tech gadgets and electronic devices', '#667C89', 1),
('Gift Cards', 'gift-cards', 'Vouchers and gift certificates', '#F39C12', 2),
('Experiences', 'experiences', 'Travel, events, and unique experiences', '#E74C3C', 3),
('Books & Education', 'books-education', 'Learning materials and educational content', '#3498DB', 4),
('Health & Wellness', 'health-wellness', 'Fitness and wellness products', '#27AE60', 5),
('Home & Office', 'home-office', 'Items for home and workplace', '#8E44AD', 6);

-- Subcategories examples
INSERT INTO "reward_categories" ("name", "slug", "description", "parent_id", "sort_order") VALUES
('Smartphones', 'smartphones', 'Mobile phones and accessories', 1, 1),
('Laptops', 'laptops', 'Portable computers and accessories', 1, 2),
('Amazon Gift Cards', 'amazon-gift-cards', 'Amazon vouchers in various amounts', 2, 1),
('Restaurant Vouchers', 'restaurant-vouchers', 'Dining experiences and food delivery', 2, 2);

-- ============================================================================
-- VALIDATION & HEALTH CHECK QUERIES
-- ============================================================================

-- Check business logic integrity
SELECT 
  'Company Values' as entity,
  COUNT(*) as total,
  COUNT(CASE WHEN active THEN 1 END) as active_count
FROM company_values
UNION ALL
SELECT 
  'Reward Categories' as entity,
  COUNT(*) as total,
  COUNT(CASE WHEN active THEN 1 END) as active_count
FROM reward_categories
UNION ALL
SELECT 
  'Compliment Reactions' as entity,
  COUNT(*) as total,
  COUNT(DISTINCT compliment_id) as unique_compliments
FROM compliment_reactions;

-- Verify referential integrity
SELECT 
  c.table_name,
  c.constraint_name,
  c.constraint_type
FROM information_schema.table_constraints c
WHERE c.table_schema = 'public'
  AND c.constraint_type IN ('FOREIGN KEY', 'CHECK', 'UNIQUE')
  AND c.table_name IN (
    'company_values', 'coin_transactions', 'compliment_reactions', 
    'compliment_comments', 'reward_categories', 'initiative_participants',
    'reward_wishlist', 'notifications'
  )
ORDER BY c.table_name, c.constraint_type;

-- ============================================================================
-- NOTES FOR PART 3
-- ============================================================================

/*
PART 2 COMPLETE - Enhanced business logic and structured systems ready

Features added:
✅ Structured company values with UI theming support
✅ Comprehensive coin transaction tracking with audit trail
✅ Social features for compliments (reactions, comments)
✅ Hierarchical reward categorization system
✅ Initiative participation tracking beyond credits
✅ User wishlist system for rewards
✅ Foundation notification system
✅ Business rule validations and constraints
✅ Performance optimization views
✅ Business intelligence foundations

Next (Part 3 - Security & Compliance):
- Advanced user security (MFA, login tracking)
- Rate limiting and fraud prevention
- Comprehensive audit logging for compliance
- GDPR consent management
- Data encryption for sensitive information
- Session management and security
*/ 