-- ============================================================================
-- VALORIZE PLATFORM - PART 3: SECURITY & COMPLIANCE
-- Database Migration Phase 3 - Enterprise Security and Regulatory Compliance
-- ============================================================================

-- This file implements enterprise-grade security and compliance features:
-- - Advanced user security (MFA, login tracking, account lockout)
-- - Rate limiting and fraud prevention systems
-- - Comprehensive audit logging for regulatory compliance
-- - GDPR consent management and data protection
-- - Encrypted sensitive data storage
-- - Session management and security monitoring

-- PREREQUISITES: Part 1 and Part 2 must be executed first

-- ============================================================================
-- ADVANCED USER SECURITY SYSTEM
-- ============================================================================

-- Separate security-related user data from profile data
CREATE TABLE "user_security" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int NOT NULL,
  "password_hash" text NOT NULL, -- bcrypt hash with high salt rounds (12+)
  "password_changed_at" timestamptz NOT NULL DEFAULT NOW(),
  "failed_login_attempts" int NOT NULL DEFAULT 0,
  "locked_until" timestamptz,
  "last_login_at" timestamptz,
  "last_login_ip" inet,
  "last_login_user_agent" text,
  "mfa_enabled" boolean NOT NULL DEFAULT false,
  "mfa_secret" text, -- Encrypted TOTP secret (base32)
  "mfa_backup_codes" text[], -- Encrypted one-time backup codes
  "password_reset_token" varchar(255),
  "password_reset_expires" timestamptz,
  "email_verification_token" varchar(255),
  "email_verified_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW()
);

-- Add foreign key and constraints
ALTER TABLE "user_security" ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id") ON DELETE CASCADE;

-- Security constraints
ALTER TABLE "user_security" ADD CONSTRAINT "check_failed_attempts" 
  CHECK ("failed_login_attempts" >= 0 AND "failed_login_attempts" <= 10);

ALTER TABLE "user_security" ADD CONSTRAINT "check_password_not_empty"
  CHECK (LENGTH(TRIM("password_hash")) > 0);

-- Security indexes
CREATE INDEX "idx_user_security_user" ON "user_security" ("id_user");
CREATE INDEX "idx_user_security_login_attempts" ON "user_security" ("failed_login_attempts", "locked_until");
CREATE INDEX "idx_user_security_password_reset" ON "user_security" ("password_reset_token", "password_reset_expires");
CREATE INDEX "idx_user_security_email_verification" ON "user_security" ("email_verification_token");

-- ============================================================================
-- RATE LIMITING & FRAUD PREVENTION
-- ============================================================================

-- Database-level rate limiting for various endpoints and operations
CREATE TABLE "rate_limits" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "ip_address" inet,
  "endpoint" varchar(100) NOT NULL,
  "operation" varchar(50), -- LOGIN, COMPLIMENT_SEND, REWARD_CLAIM, etc.
  "attempts" int NOT NULL DEFAULT 1,
  "window_start" timestamptz NOT NULL DEFAULT NOW(),
  "window_duration" interval NOT NULL DEFAULT '1 hour',
  "blocked_until" timestamptz,
  "severity" varchar(20) NOT NULL DEFAULT 'LOW', -- LOW, MEDIUM, HIGH, CRITICAL
  "metadata" jsonb, -- Additional context (user agent, etc.)
  "created_at" timestamptz NOT NULL DEFAULT NOW()
);

-- Rate limiting constraints
ALTER TABLE "rate_limits" ADD CONSTRAINT "check_attempts_positive" 
  CHECK ("attempts" > 0);

ALTER TABLE "rate_limits" ADD CONSTRAINT "check_valid_severity"
  CHECK ("severity" IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));

-- Rate limiting indexes
CREATE INDEX "idx_rate_limits_user_endpoint" ON "rate_limits" ("user_id", "endpoint", "window_start");
CREATE INDEX "idx_rate_limits_ip_endpoint" ON "rate_limits" ("ip_address", "endpoint", "window_start");
CREATE INDEX "idx_rate_limits_blocked" ON "rate_limits" ("blocked_until") WHERE "blocked_until" IS NOT NULL;
CREATE INDEX "idx_rate_limits_severity" ON "rate_limits" ("severity", "created_at");

-- ============================================================================
-- COMPREHENSIVE AUDIT LOGGING
-- ============================================================================

-- Enterprise audit logs for regulatory compliance (SOX, GDPR, etc.)
CREATE TABLE "audit_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "admin_user_id" int, -- If action performed by admin
  "action" varchar(50) NOT NULL, -- CREATE, UPDATE, DELETE, LOGIN, LOGOUT, etc.
  "entity_type" varchar(50), -- USER, COMPLIMENT, REWARD, etc.
  "entity_id" varchar(50), -- ID of the affected entity
  "old_values" jsonb, -- Previous state (for updates/deletes)
  "new_values" jsonb, -- New state (for creates/updates)
  "ip_address" inet,
  "user_agent" text,
  "session_id" varchar(255),
  "request_id" varchar(255), -- For request tracing
  "severity" varchar(20) NOT NULL DEFAULT 'INFO', -- DEBUG, INFO, WARN, ERROR, CRITICAL
  "compliance_flag" boolean NOT NULL DEFAULT false, -- Mark for compliance reporting
  "timestamp" timestamptz NOT NULL DEFAULT NOW()
);

-- Audit log indexes for performance and compliance queries
CREATE INDEX "idx_audit_logs_user_action" ON "audit_logs" ("user_id", "action", "timestamp");
CREATE INDEX "idx_audit_logs_entity" ON "audit_logs" ("entity_type", "entity_id");
CREATE INDEX "idx_audit_logs_timestamp" ON "audit_logs" ("timestamp");
CREATE INDEX "idx_audit_logs_compliance" ON "audit_logs" ("compliance_flag", "timestamp") WHERE "compliance_flag" = true;
CREATE INDEX "idx_audit_logs_severity" ON "audit_logs" ("severity", "timestamp");
CREATE INDEX "idx_audit_logs_admin" ON "audit_logs" ("admin_user_id", "timestamp");

-- ============================================================================
-- GDPR COMPLIANCE & DATA PROTECTION
-- ============================================================================

-- User consent management for GDPR compliance
CREATE TABLE "user_consents" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "consent_type" varchar(50) NOT NULL, -- MARKETING, ANALYTICS, COOKIES, PROFILING, etc.
  "granted" boolean NOT NULL,
  "ip_address" inet,
  "user_agent" text,
  "granted_at" timestamptz NOT NULL DEFAULT NOW(),
  "withdrawn_at" timestamptz,
  "version" varchar(10) NOT NULL DEFAULT '1.0', -- Privacy policy version
  "source" varchar(50) NOT NULL DEFAULT 'WEB', -- WEB, MOBILE, API, etc.
  "metadata" jsonb -- Additional consent context
);

-- Add foreign key and constraints
ALTER TABLE "user_consents" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;

ALTER TABLE "user_consents" ADD CONSTRAINT "check_consent_withdrawn_logic"
  CHECK (
    ("granted" = true AND "withdrawn_at" IS NULL) OR
    ("granted" = false AND "withdrawn_at" IS NOT NULL AND "withdrawn_at" >= "granted_at")
  );

-- Consent indexes
CREATE INDEX "idx_user_consents_user_type" ON "user_consents" ("user_id", "consent_type");
CREATE INDEX "idx_user_consents_active" ON "user_consents" ("user_id", "consent_type", "granted") WHERE "granted" = true AND "withdrawn_at" IS NULL;
CREATE INDEX "idx_user_consents_timestamp" ON "user_consents" ("granted_at");

-- Encrypted storage for sensitive personal data
CREATE TABLE "encrypted_personal_data" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "data_type" varchar(50) NOT NULL, -- CPF, PHONE, SSN, etc.
  "encrypted_value" text NOT NULL, -- AES-256-GCM encrypted data
  "hash_value" varchar(64), -- SHA-256 hash for searching/comparison without decryption
  "encryption_key_id" varchar(50) NOT NULL, -- Reference to encryption key (for rotation)
  "encryption_algorithm" varchar(50) NOT NULL DEFAULT 'AES-256-GCM',
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE("user_id", "data_type") -- One record per user per data type
);

-- Add foreign key and constraints
ALTER TABLE "encrypted_personal_data" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;

ALTER TABLE "encrypted_personal_data" ADD CONSTRAINT "check_encrypted_value_not_empty"
  CHECK (LENGTH(TRIM("encrypted_value")) > 0);

-- Encrypted data indexes
CREATE INDEX "idx_encrypted_data_user" ON "encrypted_personal_data" ("user_id");
CREATE INDEX "idx_encrypted_data_type" ON "encrypted_personal_data" ("data_type");
CREATE INDEX "idx_encrypted_data_hash" ON "encrypted_personal_data" ("hash_value"); -- For searching
CREATE INDEX "idx_encrypted_data_key" ON "encrypted_personal_data" ("encryption_key_id");

-- ============================================================================
-- SECURE SESSION MANAGEMENT
-- ============================================================================

-- Comprehensive session tracking for security monitoring
CREATE TABLE "user_sessions" (
  "id" varchar(255) PRIMARY KEY, -- JWT token ID or session token
  "user_id" int NOT NULL,
  "session_type" varchar(20) NOT NULL DEFAULT 'WEB', -- WEB, MOBILE, API
  "ip_address" inet,
  "user_agent" text,
  "device_fingerprint" varchar(255), -- Browser/device fingerprint for security
  "location" jsonb, -- Geolocation data (city, country, etc.)
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  "revoked_reason" varchar(100), -- LOGOUT, SECURITY, ADMIN_ACTION, etc.
  "last_activity" timestamptz NOT NULL DEFAULT NOW(),
  "activity_count" int NOT NULL DEFAULT 1,
  "is_suspicious" boolean NOT NULL DEFAULT false,
  "metadata" jsonb -- Additional session context
);

-- Add foreign key and constraints
ALTER TABLE "user_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE;

ALTER TABLE "user_sessions" ADD CONSTRAINT "check_session_times"
  CHECK ("expires_at" > "created_at" AND ("revoked_at" IS NULL OR "revoked_at" >= "created_at"));

-- Session indexes for performance and security
CREATE INDEX "idx_user_sessions_user" ON "user_sessions" ("user_id", "expires_at");
CREATE INDEX "idx_user_sessions_expires" ON "user_sessions" ("expires_at") WHERE "revoked_at" IS NULL;
CREATE INDEX "idx_user_sessions_active" ON "user_sessions" ("user_id") WHERE "revoked_at" IS NULL AND "expires_at" > NOW();
CREATE INDEX "idx_user_sessions_suspicious" ON "user_sessions" ("is_suspicious", "created_at") WHERE "is_suspicious" = true;
CREATE INDEX "idx_user_sessions_ip" ON "user_sessions" ("ip_address", "created_at");

-- ============================================================================
-- DATA RETENTION & PRIVACY
-- ============================================================================

-- Soft delete support for main tables (GDPR right to be forgotten)
ALTER TABLE "user" ADD COLUMN "deleted_at" timestamptz;
ALTER TABLE "initiatives" ADD COLUMN "deleted_at" timestamptz;
ALTER TABLE "rewards" ADD COLUMN "deleted_at" timestamptz;
ALTER TABLE "address" ADD COLUMN "deleted_at" timestamptz;

-- Data retention policies for automated cleanup
CREATE TABLE "data_retention_policies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_name" varchar(50) NOT NULL,
  "retention_days" int NOT NULL,
  "deletion_strategy" varchar(20) NOT NULL, -- SOFT, HARD, ARCHIVE
  "last_cleanup" timestamptz,
  "active" boolean NOT NULL DEFAULT true,
  "description" text,
  "created_at" timestamptz NOT NULL DEFAULT NOW()
);

-- Data retention constraints
ALTER TABLE "data_retention_policies" ADD CONSTRAINT "check_retention_days_positive"
  CHECK ("retention_days" > 0);

ALTER TABLE "data_retention_policies" ADD CONSTRAINT "check_valid_deletion_strategy"
  CHECK ("deletion_strategy" IN ('SOFT', 'HARD', 'ARCHIVE'));

-- Partial indexes for soft-deleted records (better performance)
CREATE INDEX "idx_user_active" ON "user" ("id") WHERE "deleted_at" IS NULL;
CREATE INDEX "idx_initiatives_active" ON "initiatives" ("id") WHERE "deleted_at" IS NULL;
CREATE INDEX "idx_rewards_active_not_deleted" ON "rewards" ("active") WHERE "deleted_at" IS NULL;

-- ============================================================================
-- SECURITY MONITORING & ALERTING
-- ============================================================================

-- Security events for monitoring and alerting
CREATE TABLE "security_events" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_type" varchar(50) NOT NULL, -- FAILED_LOGIN, SUSPICIOUS_ACTIVITY, ACCOUNT_LOCKED, etc.
  "severity" varchar(20) NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
  "user_id" int,
  "ip_address" inet,
  "user_agent" text,
  "description" text NOT NULL,
  "event_data" jsonb, -- Additional event context
  "resolved" boolean NOT NULL DEFAULT false,
  "resolved_at" timestamptz,
  "resolved_by" int, -- Admin user who resolved
  "resolution_notes" text,
  "created_at" timestamptz NOT NULL DEFAULT NOW()
);

-- Security event constraints
ALTER TABLE "security_events" ADD CONSTRAINT "check_valid_event_severity"
  CHECK ("severity" IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));

-- Security event indexes
CREATE INDEX "idx_security_events_type" ON "security_events" ("event_type", "created_at");
CREATE INDEX "idx_security_events_severity" ON "security_events" ("severity", "created_at");
CREATE INDEX "idx_security_events_user" ON "security_events" ("user_id", "created_at");
CREATE INDEX "idx_security_events_unresolved" ON "security_events" ("resolved", "created_at") WHERE "resolved" = false;
CREATE INDEX "idx_security_events_ip" ON "security_events" ("ip_address", "created_at");

-- ============================================================================
-- COMPLIANCE TRIGGERS & FUNCTIONS
-- ============================================================================

-- Function for automatic audit logging
CREATE OR REPLACE FUNCTION log_data_changes()
RETURNS TRIGGER AS $$
DECLARE
  audit_user_id INT;
  audit_admin_id INT;
BEGIN
  -- Extract user IDs from the record
  audit_user_id := CASE 
    WHEN TG_OP = 'DELETE' THEN 
      CASE WHEN OLD ? 'id' THEN (OLD->>'id')::INT ELSE NULL END
    ELSE 
      CASE WHEN NEW ? 'id' THEN (NEW->>'id')::INT ELSE NULL END
  END;

  -- Determine if this is an admin action (you'll need to implement session context)
  audit_admin_id := current_setting('app.current_admin_user_id', true)::INT;

  INSERT INTO "audit_logs" (
    "user_id",
    "admin_user_id",
    "action", 
    "entity_type",
    "entity_id",
    "old_values",
    "new_values",
    "ip_address",
    "user_agent",
    "session_id",
    "compliance_flag",
    "timestamp"
  ) VALUES (
    audit_user_id,
    audit_admin_id,
    TG_OP,
    TG_TABLE_NAME,
    CASE WHEN TG_OP = 'DELETE' THEN OLD->>'id' ELSE NEW->>'id' END,
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN row_to_json(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN row_to_json(NEW) ELSE NULL END,
    inet(current_setting('app.current_ip_address', true)),
    current_setting('app.current_user_agent', true),
    current_setting('app.current_session_id', true),
    true, -- Mark as compliance-relevant
    NOW()
  );
  
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
EXCEPTION
  WHEN OTHERS THEN
    -- Log audit failure but don't fail the original operation
    RAISE WARNING 'Audit logging failed: %', SQLERRM;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Apply audit triggers to critical tables
CREATE TRIGGER audit_user_changes 
  AFTER INSERT OR UPDATE OR DELETE ON "user"
  FOR EACH ROW EXECUTE FUNCTION log_data_changes();

CREATE TRIGGER audit_compliment_changes 
  AFTER INSERT OR UPDATE OR DELETE ON "compliment"
  FOR EACH ROW EXECUTE FUNCTION log_data_changes();

CREATE TRIGGER audit_redeem_changes 
  AFTER INSERT OR UPDATE OR DELETE ON "redeem"
  FOR EACH ROW EXECUTE FUNCTION log_data_changes();

CREATE TRIGGER audit_coin_transactions_changes
  AFTER INSERT OR UPDATE OR DELETE ON "coin_transactions"
  FOR EACH ROW EXECUTE FUNCTION log_data_changes();

-- Function for session activity tracking
CREATE OR REPLACE FUNCTION update_session_activity()
RETURNS TRIGGER AS $$
BEGIN
  -- Update last activity timestamp and increment activity count
  UPDATE "user_sessions" 
  SET 
    "last_activity" = NOW(),
    "activity_count" = "activity_count" + 1
  WHERE "id" = current_setting('app.current_session_id', true)
    AND "revoked_at" IS NULL
    AND "expires_at" > NOW();
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- SECURITY HELPER FUNCTIONS
-- ============================================================================

-- Function to check if user is locked out
CREATE OR REPLACE FUNCTION is_user_locked(user_email VARCHAR)
RETURNS BOOLEAN AS $$
DECLARE
  lock_until TIMESTAMPTZ;
BEGIN
  SELECT us.locked_until INTO lock_until
  FROM "user" u
  JOIN "user_security" us ON u.id = us.id_user
  WHERE u.email = user_email AND u.active = true;
  
  RETURN (lock_until IS NOT NULL AND lock_until > NOW());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to record login attempt
CREATE OR REPLACE FUNCTION record_login_attempt(
  user_email VARCHAR,
  success BOOLEAN,
  ip_addr INET,
  user_agent_str TEXT
)
RETURNS VOID AS $$
DECLARE
  user_id_var INT;
  current_attempts INT;
BEGIN
  -- Get user ID
  SELECT u.id INTO user_id_var
  FROM "user" u
  WHERE u.email = user_email AND u.active = true;
  
  IF user_id_var IS NULL THEN
    RETURN; -- User not found
  END IF;
  
  IF success THEN
    -- Reset failed attempts on successful login
    UPDATE "user_security" 
    SET 
      "failed_login_attempts" = 0,
      "locked_until" = NULL,
      "last_login_at" = NOW(),
      "last_login_ip" = ip_addr,
      "last_login_user_agent" = user_agent_str
    WHERE "id_user" = user_id_var;
  ELSE
    -- Increment failed attempts
    UPDATE "user_security" 
    SET 
      "failed_login_attempts" = "failed_login_attempts" + 1,
      "locked_until" = CASE 
        WHEN "failed_login_attempts" + 1 >= 5 THEN NOW() + INTERVAL '30 minutes'
        ELSE NULL
      END
    WHERE "id_user" = user_id_var
    RETURNING "failed_login_attempts" INTO current_attempts;
    
    -- Create security event for failed login
    INSERT INTO "security_events" (
      "event_type", "severity", "user_id", "ip_address", "user_agent", 
      "description", "event_data"
    ) VALUES (
      'FAILED_LOGIN',
      CASE WHEN current_attempts >= 5 THEN 'HIGH' ELSE 'MEDIUM' END,
      user_id_var,
      ip_addr,
      user_agent_str,
      format('Failed login attempt #%s for user %s', current_attempts, user_email),
      jsonb_build_object('attempt_count', current_attempts, 'locked', current_attempts >= 5)
    );
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- UPDATE TRIGGERS FOR SECURITY TABLES
-- ============================================================================

CREATE TRIGGER update_user_security_updated_at BEFORE UPDATE ON "user_security" 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_encrypted_data_updated_at BEFORE UPDATE ON "encrypted_personal_data" 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- INITIAL SECURITY DATA
-- ============================================================================

-- Default data retention policies
INSERT INTO "data_retention_policies" ("table_name", "retention_days", "deletion_strategy", "description") VALUES
('audit_logs', 2555, 'ARCHIVE', 'Legal requirement: 7 years for financial compliance'),
('security_events', 1095, 'SOFT', 'Security monitoring: 3 years for analysis'),
('user_sessions', 90, 'HARD', 'Session cleanup: 90 days for performance'),
('rate_limits', 30, 'HARD', 'Rate limit cleanup: 30 days for performance'),
('user_consents', 2555, 'ARCHIVE', 'GDPR requirement: 7 years for consent proof'),
('notifications', 365, 'SOFT', 'User notifications: 1 year for user experience');

-- Default rate limiting rules (these would be managed by the application)
INSERT INTO "rate_limits" ("endpoint", "operation", "window_duration", "severity") VALUES
('/api/auth/login', 'LOGIN', '15 minutes', 'HIGH'),
('/api/compliments/send', 'COMPLIMENT_SEND', '1 hour', 'MEDIUM'),
('/api/rewards/redeem', 'REWARD_CLAIM', '1 hour', 'MEDIUM'),
('/api/users/password-reset', 'PASSWORD_RESET', '1 hour', 'HIGH');

-- ============================================================================
-- SECURITY VIEWS FOR MONITORING
-- ============================================================================

-- Active security threats view
CREATE VIEW "v_security_threats" AS
SELECT 
  se.event_type,
  se.severity,
  COUNT(*) as event_count,
  COUNT(DISTINCT se.user_id) as affected_users,
  COUNT(DISTINCT se.ip_address) as unique_ips,
  MAX(se.created_at) as latest_event,
  COUNT(CASE WHEN se.resolved = false THEN 1 END) as unresolved_count
FROM "security_events" se
WHERE se.created_at >= NOW() - INTERVAL '24 hours'
GROUP BY se.event_type, se.severity
ORDER BY 
  CASE se.severity 
    WHEN 'CRITICAL' THEN 1 
    WHEN 'HIGH' THEN 2 
    WHEN 'MEDIUM' THEN 3 
    ELSE 4 
  END, event_count DESC;

-- User security status view
CREATE VIEW "v_user_security_status" AS
SELECT 
  u.id,
  u.email,
  u.name,
  us.mfa_enabled,
  us.email_verified_at IS NOT NULL as email_verified,
  us.failed_login_attempts,
  us.locked_until IS NOT NULL AND us.locked_until > NOW() as currently_locked,
  us.last_login_at,
  (
    SELECT COUNT(*) 
    FROM user_sessions sess 
    WHERE sess.user_id = u.id 
      AND sess.revoked_at IS NULL 
      AND sess.expires_at > NOW()
  ) as active_sessions,
  (
    SELECT COUNT(*) 
    FROM security_events se 
    WHERE se.user_id = u.id 
      AND se.created_at >= NOW() - INTERVAL '30 days'
  ) as recent_security_events
FROM "user" u
LEFT JOIN "user_security" us ON u.id = us.id_user
WHERE u.active = true AND u.deleted_at IS NULL;

-- ============================================================================
-- VALIDATION QUERIES
-- ============================================================================

-- Security table validation
SELECT 
  'Security Implementation' as check_type,
  COUNT(DISTINCT t.table_name) as security_tables_count,
  COUNT(DISTINCT i.indexname) as security_indexes_count,
  COUNT(DISTINCT p.proname) as security_functions_count
FROM information_schema.tables t
LEFT JOIN pg_indexes i ON t.table_name = i.tablename
LEFT JOIN pg_proc p ON p.proname LIKE '%security%' OR p.proname LIKE '%audit%'
WHERE t.table_schema = 'public' 
  AND t.table_name IN (
    'user_security', 'rate_limits', 'audit_logs', 'user_consents',
    'encrypted_personal_data', 'user_sessions', 'security_events', 'data_retention_policies'
  );

-- Compliance features check
SELECT 
  'GDPR Compliance' as feature,
  CASE WHEN EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name = 'user_consents') 
    THEN 'Implemented' ELSE 'Missing' END as status
UNION ALL
SELECT 
  'Audit Logging' as feature,
  CASE WHEN EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name = 'audit_logs') 
    THEN 'Implemented' ELSE 'Missing' END as status
UNION ALL
SELECT 
  'Data Encryption' as feature,
  CASE WHEN EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name = 'encrypted_personal_data') 
    THEN 'Implemented' ELSE 'Missing' END as status;

-- ============================================================================
-- NOTES FOR PART 4
-- ============================================================================

/*
PART 3 COMPLETE - Enterprise security and compliance features implemented

Security features added:
✅ Advanced user security with MFA support
✅ Database-level rate limiting system  
✅ Comprehensive audit logging for compliance
✅ GDPR consent management system
✅ Encrypted sensitive data storage
✅ Secure session management with monitoring
✅ Security event tracking and alerting
✅ Data retention policies for privacy compliance
✅ Security helper functions and triggers
✅ Monitoring views for security dashboard

Next (Part 4 - Internationalization):
- Multi-language support system
- User localization preferences
- Localized content for initiatives and rewards
- Multi-currency support with exchange rates
- Timezone handling and date formatting
- Cultural customization features
*/ 